--------------------------------------------------------------------------------
-- File: pkg_weights_gen.vhd
-- Description: Definitive Synaptic Weight Matrix & Neuron Parameters (FSD v2 §7.3)
-- Generated by analytic tuning procedure (tune.py / FSD v2 contract)
-- Standard: VHDL-2008, IEEE numeric_std
--------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.pkg_fsd.all;

package pkg_weights_gen is

    ----------------------------------------------------------------------------
    -- Initial Weights Table (4 Neurons x 12 Channels)
    ----------------------------------------------------------------------------
    constant DEFAULT_WEIGHTS : weight_matrix_t := (
        -- N0: TRANSIENT (Hard flags only, instant reaction)
        0 => (
            CH_CLK_FAST_H    => to_signed(16, 8),
            CH_CLK_SLOW_H    => to_signed(16, 8),
            CH_CLK_STOP_H    => to_signed(16, 8),
            CH_MMCM_UNLOCK_H => to_signed(16, 8),
            CH_V_UNDER_H     => to_signed(16, 8),
            CH_V_OVER_H      => to_signed(16, 8),
            CH_KEY_CORRUPT_H => to_signed(16, 8),
            CH_JTAG_H        => to_signed(0, 8),
            CH_CLK_SOFT      => to_signed(0, 8),
            CH_V_SOFT        => to_signed(0, 8),
            CH_SPARE_10      => to_signed(0, 8),
            CH_SPARE_11      => to_signed(0, 8)
        ),

        -- N1: REPEAT-PROBE (Soft sub-threshold repeat-attack accumulation, SCEN2)
        1 => (
            CH_CLK_FAST_H    => to_signed(4, 8),
            CH_CLK_SLOW_H    => to_signed(0, 8),
            CH_CLK_STOP_H    => to_signed(0, 8),
            CH_MMCM_UNLOCK_H => to_signed(0, 8),
            CH_V_UNDER_H     => to_signed(0, 8),
            CH_V_OVER_H      => to_signed(0, 8),
            CH_KEY_CORRUPT_H => to_signed(0, 8),
            CH_JTAG_H        => to_signed(0, 8),
            CH_CLK_SOFT      => to_signed(11, 8),
            CH_V_SOFT        => to_signed(11, 8),
            CH_SPARE_10      => to_signed(0, 8),
            CH_SPARE_11      => to_signed(0, 8)
        ),

        -- N2: COMBINED (Cross-channel & sustained anomaly detector, SCEN3)
        2 => (
            CH_CLK_FAST_H    => to_signed(2, 8),
            CH_CLK_SLOW_H    => to_signed(2, 8),
            CH_CLK_STOP_H    => to_signed(0, 8),
            CH_MMCM_UNLOCK_H => to_signed(4, 8),
            CH_V_UNDER_H     => to_signed(2, 8),
            CH_V_OVER_H      => to_signed(2, 8),
            CH_KEY_CORRUPT_H => to_signed(0, 8),
            CH_JTAG_H        => to_signed(4, 8),
            CH_CLK_SOFT      => to_signed(12, 8),
            CH_V_SOFT        => to_signed(12, 8),
            CH_SPARE_10      => to_signed(0, 8),
            CH_SPARE_11      => to_signed(0, 8)
        ),

        -- N3: SPARE (Reserved / Inactive in MVP)
        3 => (
            others => to_signed(0, 8)
        )
    );

    ----------------------------------------------------------------------------
    -- Leak Shifts M (V -= V >> M) per Neuron
    -- Design rule constraint: M <= log2(theta) - 1 => M <= 6 for theta=128
    ----------------------------------------------------------------------------
    constant DEFAULT_M_SHIFTS : m_array_t := (
        0 => 3, -- N0: M=3
        1 => 4, -- N1: M=4
        2 => 4, -- N2: M=4
        3 => 4  -- N3: M=4
    );

    ----------------------------------------------------------------------------
    -- Firing Thresholds theta per Neuron
    ----------------------------------------------------------------------------
    constant DEFAULT_THETA : theta_array_t := (
        0 => to_signed(128, 16),
        1 => to_signed(128, 16),
        2 => to_signed(128, 16),
        3 => to_signed(128, 16)
    );

end package pkg_weights_gen;
