--------------------------------------------------------------------------------
-- File: snn_weights_pkg.vhd
-- Auto-generated by export_weights.py
-- SHA-256 Hash: e9e30a9cf9ab04337cdd090b24853c49ab1011b12e5b4f0e703cf648696c0c6d
-- Generated: 2026-10-07T21:35:23.345144
--------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package snn_weights_pkg is

    type weight_array_t is array(0 to 13) of signed(7 downto 0);

    constant WEIGHTS_HASH : string := "e9e30a9cf9ab04337cdd090b24853c49ab1011b12e5b4f0e703cf648696c0c6d";
    constant VTH_PARAM    : integer := 200;
    constant LEAK_L_PARAM  : integer := 7;

    constant W : weight_array_t := (
        to_signed(10, 8),
        to_signed(5, 8),
        to_signed(15, 8),
        to_signed(-5, 8),
        to_signed(35, 8),
        to_signed(-10, 8),
        to_signed(45, 8),
        to_signed(50, 8),
        to_signed(40, 8),
        to_signed(-15, 8),
        to_signed(30, 8),
        to_signed(-10, 8),
        to_signed(40, 8),
        to_signed(80, 8)
    );

end package snn_weights_pkg;
