#!/usr/bin/env python3
"""
export_weights.py - Export Trained Weights to snn_weights_pkg.vhd with SHA-256 Hash
FSD §6.1
"""

import os
import hashlib
import datetime
from params import PARAMS

DEFAULT_WEIGHTS = [10, 5, 15, -5, 35, -10, 45, 50, 40, -15, 30, -10, 40, 80]

def export_weights(weights, vth=200, leak_l=7, out_path="rtl/snn_weights_pkg.vhd"):
    raw_bytes = bytes([w & 0xFF for w in weights])
    sha256 = hashlib.sha256(raw_bytes).hexdigest()

    w_strs = [f"to_signed({w}, 8)" for w in weights]
    w_formatted = ",\n        ".join(w_strs)

    vhdl = f"""--------------------------------------------------------------------------------
-- File: snn_weights_pkg.vhd
-- Auto-generated by export_weights.py
-- SHA-256 Hash: {sha256}
-- Generated: {datetime.datetime.now().isoformat()}
--------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package snn_weights_pkg is

    type weight_array_t is array(0 to 13) of signed(7 downto 0);

    constant WEIGHTS_HASH : string := "{sha256}";
    constant VTH_PARAM    : integer := {vth};
    constant LEAK_L_PARAM  : integer := {leak_l};

    constant W : weight_array_t := (
        {w_formatted}
    );

end package snn_weights_pkg;
"""

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(vhdl)
    print(f"Exported weights to {out_path} (SHA-256: {sha256[:12]}...)")

if __name__ == "__main__":
    export_weights(DEFAULT_WEIGHTS)
